docs: adding documentation for regressors
adaptive-machine-learning/CapyMOA pull request #120
Opened 2024-05-19 14:52 UTC by YibinSun

-- Add documenting for regressors:
```FIMTDD```
```ORTO```
```KNNRegressor```
```Passive Aggressive Regressor```
```SGD Regressor```
```SOKNL```
```SOKNLBT```
-- Update `__init__.py` accordingly

2024-05-20 06:20 UTC, hmgomes requested changes
Please see the request changes. Most of them are related to the content of the documentation for SOKNL, we need to make it more explicit what the algorithm does.

2024-05-20 06:20 UTC, hmgomes commented on src/capymoa/regressor/_soknl.py
> +    SOKNL is an extension to AdaptiveRandomForestRegressor.
SOKNL extends the AdaptiveRandomForestRegressor by limiting the number of base trees (or tree leaves) involved in predicting a given instance. This approach overrides the aggregation strategy used for voting, leading to more accurate predictions in general.

2024-05-20 06:20 UTC, hmgomes commented on src/capymoa/regressor/_soknl.py
> +    SOKNL stores abstract information for all instance seen by the leaves, use them to calculate the distance
Improve this part. What is the abstract information? What is the certain instance? You may refer to it as the instance whose target value is being predicted (or find a more concise way to refer to it :) ). Also, you are not explaining the Self-Optimising mechanism in here, and you should.

2024-05-20 06:20 UTC, hmgomes commented on src/capymoa/regressor/_soknl.py
> +
Before the reference add a "See also" for ARFReg and MOARegressor. You can refer to other classes using the syntax below (See _adaptive_random_forest.py for reference on the syntax as well)

See also :py:class:\`capymoa.regressor.AdaptiveRandomForestRegressor\`
See :py:class:\`capymoa.base.MOARegressor\` for train and predict.

2024-05-20 06:20 UTC, hmgomes commented on src/capymoa/regressor/_soknl_base_tree.py
> +    See in reference:
Just Reference, not "See in reference"

2024-05-20 06:20 UTC, hmgomes commented on src/capymoa/regressor/_soknl_base_tree.py
> +    SOKNLBT is a modification to the FIMT-DD that allows FIMT-DD to store necessary information.
SOKNLBT modifies the FIMT-DD algorithm to store information at the leaves that allows SOKNL to calculate the distance between a given instance and a leaf. 

See also... (add link to SOKNL) and (add link to FIMTDD)

2024-05-20 22:25 UTC, YibinSun commented
@hmgomes, amendments have been implemented, please take a look.

2024-05-23 05:35 UTC, hmgomes commented
thanks @YibinSun , it is looking much better now

2024-05-23 05:35 UTC, hmgomes approved these changes

2024-05-23 05:35 UTC, merged